name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args: pack
